version: "3"
services:
  user-postgres:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - ./db-data/user:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 3002:${USER_SERVICE_PORT}
    depends_on:
      - user-postgres
    volumes:
      - ./user-service:/app
    working_dir: /app

    command: /bin/bash -c "/app/start.sh"

  wallet-postgres:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${WALLET_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WALLET_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${WALLET_SERVICE_POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./db-data/wallet:/var/lib/postgresql/data

  wallet-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 3001:${WALLET_SERVICE_PORT}
    depends_on:
      - wallet-postgres
    volumes:
      - ./wallet-service:/app
    working_dir: /app
    command: /bin/bash -c "/app/start.sh"
