version: "3"
services:
  user-postgres:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}

  user-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - user-postgres
    volumes:
      - ./user-service:/app
    working_dir: /app

    command: /bin/bash -c "/app/start.sh"
